export {
  PACKAGE_VERSION,
  PROTOCOL_VERSION,
  SUPPORTED_ENGINES,
  SUPPORTED_SEVERITIES,
  SUPPORTED_OUTCOMES,
  SUPPORTED_STATUSES,
  SUPPORTED_CLASSIFICATIONS,
  SUPPORTED_SIDES,
  HUNK_WITH_LEFT_RE,
  SHA_RE,
  SHA_64_RE,
  TOKEN_RE,
  FINDING_V1,
  DISPOSITION_V1,
  PR_V1_MARKERS,
  FINDING_V3_RE,
  PSEUDO_V3_RE,
  DISPOSITION_V3_RE,
  FINDING_V1_RE,
  DISPOSITION_V1_RE,
  PROTOCOL_THREAD_MARKER_RE,
  LEGACY_THREAD_MARKER_RE,
  ROSTER_V1_MARKER,
  ROSTER_V1_RE,
  ROSTER_V2_MARKER,
  ROSTER_V2_RE,
  ROSTER_ANY_MARKER,
  PASS_V3_RE,
  COMPLETE_V3_RE,
  EXPECTED_ACTOR_ENV,
  EXPECTED_THREADS_SHA256_ENV,
  HISTORICAL_COMMENT_IDS_ENV,
  TELEMETRY_VERSION,
  TELEMETRY_MARKER_PREFIX,
  TELEMETRY_V1_MARKER,
  TELEMETRY_PASS_TYPES,
  TELEMETRY_REVIEW_TIERS,
  TELEMETRY_TRIGGERS,
  TELEMETRY_STANCES,
  TELEMETRY_STATUSES,
  TELEMETRY_TOKEN_SOURCES,
  CANONICAL_TOKEN_BUCKETS,
  OPEN_TOKEN_RE,
  PROVIDER_BUCKET_KEY_RE,
  REPO_RE,
  UTC_TIMESTAMP_RE,
} from './constants.js';

export { LedgerError, fail } from './errors.js';

export { sha256Text, sha256Bytes, requireToken, requireSha } from './hash.js';

export { parseDiffLines, validateAnchor, type DiffLines } from './diff.js';
export { classifyRangeEffect, type RangeEffect } from './effect.js';

export {
  readLegacyBody,
  readContent,
  validateContentString,
  buildFindingBody,
  buildDispositionBody,
  matchProtocol,
  matchMarkerLine,
  verifyV1Marker,
  matchPseudoV3,
  matchFinding,
  matchDisposition,
} from './protocol.js';

export {
  readResultBytes,
  readResult,
  validateResultData,
  writeResultFile,
  validateResult,
  writeBlockedResult,
  resultHead,
} from './result.js';

export {
  threadProtocolRecords,
  matchingDispositions,
  pairDispositions,
  verifyForwardTransition,
  verifyForwardTransitionOrFail,
  verifyHistoricalThreads,
  verifyBlockingNotDeferred,
  verifyThreadDispositions,
  sameRoundDispositions,
  transitionHeads,
  verifyResultEvidence,
  writeResult,
  preflightAnchor,
  postFinding,
  reopenOccurrence,
  dispose,
  reply,
  postPrComment,
  attest,
  resolve,
  resolveThreads,
  reconcile,
  verifyLedger,
} from './ledger.js';

export {
  runGh,
  jsonOutput,
  currentActor,
  assertActor,
  authenticatedRows,
  verifyHead,
  getPrFiles,
  getReviewComments,
  getIssueComments,
  verifyComment,
  verifyIssueComment,
  getPostedCommentId,
  findMatchingBody,
  postReviewComment,
  getThreadState,
  setThreadState,
  loadReviewThreads,
  parseReviewThreadPages,
  fetchReviewThreads,
  reviewThreads,
  findRootThread,
  assertThreadScope,
  execFailureDetail,
  runGit,
  isAncestor,
  verifyReviewBase,
  verifyGitTransition,
  loadHistoricalCommentIds,
  verifyPseudoV3History,
  loadAllowedHeads,
  rowsHaveHistoricalMarkers,
} from './github.js';

export {
  parseReviewers,
  matchRoster,
  buildRosterBody,
  rosterDigestInput,
  resolveRoster,
  readRoster,
  postRoster,
  attestationsAtHead,
  coverageTier,
  coverage,
  verifyCoverage,
} from './roster.js';

export { formatFindings } from './format.js';

export {
  CHANGESET_CLASSIFIER_VERSION,
  DEFAULT_PROMPT_SURFACES,
  classifyFiles,
  classifyPath,
  classifyRange,
  parseDiffPatch,
} from './changeset.js';

export {
  buildTelemetryBody,
  buildTelemetryRecord,
  emitTelemetry,
  excludeTelemetryComments,
  isTelemetryComment,
  matchTelemetry,
  prCommentSink,
  telemetryIdempotencyKey,
  validateTelemetryRecord,
} from './telemetry.js';

export type {
  SupportedEngine,
  SupportedSeverity,
  SupportedOutcome,
  SupportedStatus,
  SupportedClassification,
  SupportedSide,
  ReviewFinding,
  FindingV3Match,
  DispositionV3Match,
  FindingV1Match,
  DispositionV1Match,
  PseudoV3Match,
  LedgerResult,
  BaseResultParams,
  WriteResultParams,
  WriteBlockedParams,
  ValidateResultParams,
  PreflightAnchorParams,
  PreflightAnchorResult,
  PostFindingParams,
  PostFindingResult,
  ReopenOccurrenceParams,
  ReopenOccurrenceResult,
  DisposeParams,
  DisposeResult,
  ReplyParams,
  PostPrCommentParams,
  AttestParams,
  AttestResult,
  ResolveParams,
  ResolveResult,
  ReconcileParams,
  ReconcileResult,
  VerifyLedgerParams,
  VerifyLedgerResult,
  ThreadResolutionReport,
  GitHubCommentAuthor,
  GitHubReviewCommentNode,
  GitHubReviewThreadNode,
  GitHubRunner,
  CoverageTier,
  RosterVersion,
  RosterMatch,
  RosterV1Match,
  RosterReport,
  PostRosterParams,
  PostRosterResult,
  AttestationAtHead,
  CoverageParams,
  CoverageResult,
  ChangesetClass,
  ClassifyOptions,
  ChangedFile,
  FileClassification,
  ChangesetLines,
  Changeset,
  ChangesetReport,
  TelemetryPassType,
  TelemetryReviewTier,
  TelemetryTrigger,
  TelemetryStance,
  TelemetryStatus,
  TelemetryTokenSource,
  TelemetryTokenBucket,
  TelemetryTokenBucketInput,
  TelemetryLane,
  TelemetryLaneInput,
  TelemetryOutcomeCounts,
  TelemetryFindings,
  TelemetryFindingsInput,
  TelemetryRecord,
  BuildTelemetryParams,
  TelemetrySink,
  TelemetrySinkResult,
  EmitTelemetryResult,
} from './types.js';
